sudo: false
dist: trusty
language: ruby
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - &latest_ruby "2.6"
cache:
  bundler: true
bundler_args: --without development
script:
  - bundle exec rake
  - bundle exec rubocop
matrix:
  include:
    - rvm   : *latest_ruby
      name  : Profile Memory Allocation
      script: bundle exec rake profile_memory
    - rvm   : *latest_ruby
      name  : Interpreter Warnings Test
      env   : RUBYOPT=-w
      script: bundle exec rake
